project_id = "ymahldldyxvwjeruaxpr"

[functions.tts]
verify_jwt = false

[functions.ping]
verify_jwt = false

[functions.admin-ping]
verify_jwt = true

[functions.kingdoms-import-csv]
verify_jwt = true

[functions.notifications-list]
verify_jwt = true

[functions.notifications-read]
verify_jwt = true